version: "3.9"

services:
  users:
    build: .
    image: users-v0.0.1
    depends_on:
      - users_db
    ports:
      - 3000:5000
    environment:
      DB_HOST: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: monitor_users
      CONFIG_PORT: 5000
    networks:
      -  net-users
      -  net-micros
    volumes:
      - ./datausers/:/app/datafile

  users_db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
      -  net-users
    environment:
      POSTGRES_DB: monitor_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  net-micros:
    driver: bridge
  net-users:
    driver: bridge
  net-offers:
    driver: bridge
  net-posts:
    driver: bridge
  net-routes:
    driver: bridge
